---
name: 'Generate User Cache Mapping'
description: 'Creates json file of slack users by github or member login'
author: 'Fieldguide'
inputs:
  github_token:
    description: 'Repository GITHUB_TOKEN or personal access token secret'
    required: false
    default: ${{ github.token }}
  org:
    description: 'name of github org to fetch user list'
    required: true
  output_path:
    description: 'output of cache mapping'
    required: false
    default: 'data/github_to_slack.json'
outputs:
  raw_mapping_json:
    description: 'Raw JSON mapping of Slack user details by GitHub user'
runs:
  using: 'node20'
  main: '../../../dist/generateMapping/index.js'
branding:
  icon: bell
  color: purple
