version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
      jest:
        patterns:
          - 'jest'
          - 'ts-jest'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
