version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'Fieldguide/ci'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
