version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'Fieldguide/ci'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      eslint:
        patterns:
          - '@typescript-eslint/parser'
          - 'eslint'
          - 'eslint-*'
      typescript:
        patterns:
          - '@swc/*'
          - '@tsconfig/*'
          - 'ts-loader'
          - 'ts-node'
          - 'tsconfig-paths'
          - 'typescript'
      jest:
        patterns:
          - '@jest/globals'
          - 'jest'
          - 'ts-jest'
