name: 'Slack Deploy Pipeline Notifications'
description: 'Post deploy workflow progress notifications to Slack'
author: 'Fieldguide'
inputs:
  thread_ts:
    description: 'Initial Slack message timestamp ID'
    required: false
  conclusion:
    description: "'true' denotes last stage"
    required: false
  github_token:
    description: 'Repository GITHUB_TOKEN or personal access token secret'
    required: false
    default: ${{ github.token }}
  status:
    description: 'The current status of the job'
    required: false
    default: ${{ job.status }}
outputs:
  ts:
    description: 'Slack message timestamp ID'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: bell
  color: purple
