---
name: 'Generate Slack Deploy User Mapping'
description: 'Generate mapping of Slack user details by GitHub username for use in Slack Deploy Pipeline Notifications'
author: 'Fieldguide'
inputs:
  github_token:
    description: 'Repository GITHUB_TOKEN or personal access token secret'
    required: false
    default: ${{ github.token }}
  github_org:
    description: 'GitHub organization name from which members are fetched'
    required: true
outputs:
  json:
    description: 'JSON-serialized mapping of Slack user details by GitHub username'
runs:
  using: 'node20'
  main: '../../../dist/generateUserMapping/index.js'
branding:
  icon: bell
  color: purple
