name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

  test:
    runs-on: ubuntu-latest
    env:
      SLACK_DEPLOY_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_FOR_TESTING }}
      SLACK_DEPLOY_CHANNEL: 'C040YVCUDRR' #github_action_testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Post to Slack
        uses: ./
        id: slack

      - uses: ./
        with:
          thread_ts: ${{ steps.slack.outputs.ts }}
          conclusion: true
