name: ci
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install
      - run: npm run all

  test:
    runs-on: ubuntu-latest
    env:
      SLACK_DEPLOY_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_FOR_TESTING }}
      SLACK_DEPLOY_CHANNEL: 'C040YVCUDRR' #github_action_testing
    steps:
      - uses: actions/checkout@v3
      - name: Post to Slack
        uses: ./
        id: slack
      - uses: ./
        with:
          thread_ts: ${{ steps.slack.outputs.ts }}
          conclusion: true
