name: Release
on:
  release:
    types: [published, edited]
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true
